libtrie/src/libtrie.lo: /home/ru/CLionProjects/php-ext-libtrie/libtrie/src/libtrie.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/ru/CLionProjects/php-ext-libtrie $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/ru/CLionProjects/php-ext-libtrie/libtrie/src/libtrie.c -o libtrie/src/libtrie.lo 
libtrie/src/single_list.lo: /home/ru/CLionProjects/php-ext-libtrie/libtrie/src/single_list.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/ru/CLionProjects/php-ext-libtrie $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/ru/CLionProjects/php-ext-libtrie/libtrie/src/single_list.c -o libtrie/src/single_list.lo 
php_libtrie.lo: /home/ru/CLionProjects/php-ext-libtrie/php_libtrie.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/ru/CLionProjects/php-ext-libtrie $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/ru/CLionProjects/php-ext-libtrie/php_libtrie.c -o php_libtrie.lo 
$(phplibdir)/libtrie.la: ./libtrie.la
	$(LIBTOOL) --mode=install cp ./libtrie.la $(phplibdir)

./libtrie.la: $(shared_objects_libtrie) $(LIBTRIE_SHARED_DEPENDENCIES)
	$(LIBTOOL) --mode=link $(CC) $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS) -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_libtrie) $(LIBTRIE_SHARED_LIBADD)

